-- Radio Shows
-- 84 unique shows filling 24/7 schedule, each airing once per week

INSERT INTO shows (title, slug, description, logo_url, status, created_at) VALUES
-- SUNDAY (12 shows of 2hrs each)
('Sunday Morning Jazz', 'sunday-morning-jazz', 'Start your Sunday with smooth jazz classics', 'images/logos/2025/01/01/sunday-morning-jazz.jpg', 'active', NOW() - INTERVAL '91 days'),
('Gospel Hour', 'gospel-hour', 'Uplifting gospel music and spirituals', 'images/logos/2025/01/01/gospel-hour.jpg', 'active', NOW() - INTERVAL '90 days'),
('World Music Passport', 'world-music-passport', 'Global sounds from every continent', 'images/logos/2025/01/01/world-music-passport.jpg', 'active', NOW() - INTERVAL '89 days'),
('Classical Sundays', 'classical-sundays', 'Timeless classical compositions', 'images/logos/2025/01/01/classical-sundays.jpg', 'active', NOW() - INTERVAL '88 days'),
('Indie Mixtape', 'indie-mixtape', 'Fresh independent music discoveries', 'images/logos/2025/01/01/indie-mixtape.jpg', 'active', NOW() - INTERVAL '87 days'),
('Soul Kitchen', 'soul-kitchen', 'Classic soul, R&B, and funk', 'images/logos/2025/01/01/soul-kitchen.jpg', 'active', NOW() - INTERVAL '86 days'),
('Acoustic Sessions', 'acoustic-sessions', 'Stripped-down acoustic performances', 'images/logos/2025/01/01/acoustic-sessions.jpg', 'active', NOW() - INTERVAL '85 days'),
('Electronic Sunday', 'electronic-sunday', 'Electronic beats to end your weekend', 'images/logos/2025/01/01/electronic-sunday.jpg', 'active', NOW() - INTERVAL '84 days'),
('Reggae Vibes', 'reggae-vibes', 'Roots reggae and dancehall', 'images/logos/2025/01/01/reggae-vibes.jpg', 'active', NOW() - INTERVAL '83 days'),
('Blues After Dark', 'blues-after-dark', 'Late night blues classics', 'images/logos/2025/01/01/blues-after-dark.jpg', 'active', NOW() - INTERVAL '82 days'),
('Experimental Sounds', 'experimental-sounds', 'Avant-garde and boundary-pushing music', 'images/logos/2025/01/01/experimental-sounds.jpg', 'active', NOW() - INTERVAL '81 days'),
('Midnight Ambient', 'midnight-ambient', 'Atmospheric soundscapes for late night', 'images/logos/2025/01/01/midnight-ambient.jpg', 'active', NOW() - INTERVAL '80 days'),

-- MONDAY (mix of 1hr and 2hr shows)
('Monday Morning Wake Up', 'monday-morning-wake-up', 'Energetic music to start your week', 'images/logos/2025/01/01/monday-morning-wake-up.jpg', 'active', NOW() - INTERVAL '79 days'),
('Coffee & Classics', 'coffee-and-classics', 'Classical music for your morning routine', 'images/logos/2025/01/01/coffee-and-classics.jpg', 'active', NOW() - INTERVAL '78 days'),
('Folk Tales', 'folk-tales', 'Folk music and storytelling', 'images/logos/2025/01/01/folk-tales.jpg', 'active', NOW() - INTERVAL '77 days'),
('Midday Mix', 'midday-mix', 'Eclectic midday music mix', 'images/logos/2025/01/01/midday-mix.jpg', 'active', NOW() - INTERVAL '76 days'),
('Latin Grooves', 'latin-grooves', 'Salsa, cumbia, and Latin rhythms', 'images/logos/2025/01/01/latin-grooves.jpg', 'active', NOW() - INTERVAL '75 days'),
('Rock Solid', 'rock-solid', 'Classic rock anthems', 'images/logos/2025/01/01/rock-solid.jpg', 'active', NOW() - INTERVAL '74 days'),
('Drive Time', 'drive-time', 'Perfect soundtrack for your commute', 'images/logos/2025/01/01/drive-time.jpg', 'active', NOW() - INTERVAL '73 days'),
('Hip-Hop Fundamentals', 'hip-hop-fundamentals', 'Essential hip-hop tracks', 'images/logos/2025/01/01/hip-hop-fundamentals.jpg', 'active', NOW() - INTERVAL '72 days'),
('Jazz Lounge', 'jazz-lounge', 'Sophisticated evening jazz', 'images/logos/2025/01/01/jazz-lounge.jpg', 'active', NOW() - INTERVAL '71 days'),
('Punk Power Hour', 'punk-power-hour', 'High-energy punk rock', 'images/logos/2025/01/01/punk-power-hour.jpg', 'active', NOW() - INTERVAL '70 days'),
('Metal Madness', 'metal-madness', 'Heavy metal and hard rock', 'images/logos/2025/01/01/metal-madness.jpg', 'active', NOW() - INTERVAL '69 days'),
('Late Night Chill', 'late-night-chill', 'Downtempo beats for night owls', 'images/logos/2025/01/01/late-night-chill.jpg', 'active', NOW() - INTERVAL '68 days'),
('Graveyard Shift', 'graveyard-shift', 'Music for the wee hours', 'images/logos/2025/01/01/graveyard-shift.jpg', 'active', NOW() - INTERVAL '67 days'),

-- TUESDAY
('Tuesday Sunrise', 'tuesday-sunrise', 'Gentle morning sounds', 'images/logos/2025/01/01/tuesday-sunrise.jpg', 'active', NOW() - INTERVAL '66 days'),
('Morning Brew', 'morning-brew', 'Coffee-fueled eclectic mix', 'images/logos/2025/01/01/morning-brew.jpg', 'active', NOW() - INTERVAL '65 days'),
('Singer-Songwriter Showcase', 'singer-songwriter-showcase', 'Spotlighting lyrical storytellers', 'images/logos/2025/01/01/singer-songwriter-showcase.jpg', 'active', NOW() - INTERVAL '64 days'),
('World Beat', 'world-beat', 'Percussion and rhythm from around the globe', 'images/logos/2025/01/01/world-beat.jpg', 'active', NOW() - INTERVAL '63 days'),
('Indie Rock Hour', 'indie-rock-hour', 'Independent rock discoveries', 'images/logos/2025/01/01/indie-rock-hour.jpg', 'active', NOW() - INTERVAL '62 days'),
('Soul Stirrers', 'soul-stirrers', 'Deep soul and classic R&B', 'images/logos/2025/01/01/soul-stirrers.jpg', 'active', NOW() - INTERVAL '61 days'),
('Alternative Nation', 'alternative-nation', 'Alternative rock past and present', 'images/logos/2025/01/01/alternative-nation.jpg', 'active', NOW() - INTERVAL '60 days'),
('Electronic Evolution', 'electronic-evolution', 'The progression of electronic music', 'images/logos/2025/01/01/electronic-evolution.jpg', 'active', NOW() - INTERVAL '59 days'),
('Country Roads', 'country-roads', 'Traditional and modern country', 'images/logos/2025/01/01/country-roads.jpg', 'active', NOW() - INTERVAL '58 days'),
('Funk Sessions', 'funk-sessions', 'Get down with classic funk', 'images/logos/2025/01/01/funk-sessions.jpg', 'active', NOW() - INTERVAL '57 days'),
('Jazz Standards', 'jazz-standards', 'Timeless jazz classics', 'images/logos/2025/01/01/jazz-standards.jpg', 'active', NOW() - INTERVAL '56 days'),
('Noise & Space', 'noise-and-space', 'Experimental and noise music', 'images/logos/2025/01/01/noise-and-space.jpg', 'active', NOW() - INTERVAL '55 days'),
('Deep Night Mix', 'deep-night-mix', 'Music for the deep night hours', 'images/logos/2025/01/01/deep-night-mix.jpg', 'active', NOW() - INTERVAL '54 days'),

-- WEDNESDAY
('Midweek Morning', 'midweek-morning', 'Hump day starts here', 'images/logos/2025/01/01/midweek-morning.jpg', 'active', NOW() - INTERVAL '53 days'),
('Classical Interlude', 'classical-interlude', 'Classical music break', 'images/logos/2025/01/01/classical-interlude.jpg', 'active', NOW() - INTERVAL '52 days'),
('Folk Underground', 'folk-underground', 'Deep folk and Americana', 'images/logos/2025/01/01/folk-underground.jpg', 'active', NOW() - INTERVAL '51 days'),
('Lunch Hour Favorites', 'lunch-hour-favorites', 'Midday music you love', 'images/logos/2025/01/01/lunch-hour-favorites.jpg', 'active', NOW() - INTERVAL '50 days'),
('Afrobeat Express', 'afrobeat-express', 'West African grooves', 'images/logos/2025/01/01/afrobeat-express.jpg', 'active', NOW() - INTERVAL '49 days'),
('Psychedelic Journey', 'psychedelic-journey', 'Mind-expanding psych rock', 'images/logos/2025/01/01/psychedelic-journey.jpg', 'active', NOW() - INTERVAL '48 days'),
('Hip-Hop Heritage', 'hip-hop-heritage', 'Golden age to modern hip-hop', 'images/logos/2025/01/01/hip-hop-heritage.jpg', 'active', NOW() - INTERVAL '47 days'),
('Dub Vibrations', 'dub-vibrations', 'Dub, roots, and bass', 'images/logos/2025/01/01/dub-vibrations.jpg', 'active', NOW() - INTERVAL '46 days'),
('Shoegaze & Dream Pop', 'shoegaze-and-dream-pop', 'Ethereal guitar soundscapes', 'images/logos/2025/01/01/shoegaze-and-dream-pop.jpg', 'active', NOW() - INTERVAL '45 days'),
('Jazz Fusion', 'jazz-fusion', 'Where jazz meets rock and funk', 'images/logos/2025/01/01/jazz-fusion.jpg', 'active', NOW() - INTERVAL '44 days'),
('Post-Rock Horizons', 'post-rock-horizons', 'Instrumental post-rock epics', 'images/logos/2025/01/01/post-rock-horizons.jpg', 'active', NOW() - INTERVAL '43 days'),
('Industrial Underground', 'industrial-underground', 'Industrial and EBM', 'images/logos/2025/01/01/industrial-underground.jpg', 'active', NOW() - INTERVAL '42 days'),
('Night Drones', 'night-drones', 'Drone and dark ambient', 'images/logos/2025/01/01/night-drones.jpg', 'active', NOW() - INTERVAL '41 days'),

-- THURSDAY
('Thursday Wake-Up Call', 'thursday-wake-up-call', 'Almost Friday energy', 'images/logos/2025/01/01/thursday-wake-up-call.jpg', 'active', NOW() - INTERVAL '40 days'),
('Baroque & Beyond', 'baroque-and-beyond', 'Early classical music', 'images/logos/2025/01/01/baroque-and-beyond.jpg', 'active', NOW() - INTERVAL '39 days'),
('Bluegrass & Old Time', 'bluegrass-and-old-time', 'Traditional Americana', 'images/logos/2025/01/01/bluegrass-and-old-time.jpg', 'active', NOW() - INTERVAL '38 days'),
('Tropical Sounds', 'tropical-sounds', 'Caribbean and island music', 'images/logos/2025/01/01/tropical-sounds.jpg', 'active', NOW() - INTERVAL '37 days'),
('Garage Rock Revival', 'garage-rock-revival', 'Raw, energetic rock & roll', 'images/logos/2025/01/01/garage-rock-revival.jpg', 'active', NOW() - INTERVAL '36 days'),
('New Wave Nostalgia', 'new-wave-nostalgia', '80s new wave classics', 'images/logos/2025/01/01/new-wave-nostalgia.jpg', 'active', NOW() - INTERVAL '35 days'),
('Techno Territory', 'techno-territory', 'Pure techno beats', 'images/logos/2025/01/01/techno-territory.jpg', 'active', NOW() - INTERVAL '34 days'),
('Ska & Rocksteady', 'ska-and-rocksteady', 'Upbeat ska grooves', 'images/logos/2025/01/01/ska-and-rocksteady.jpg', 'active', NOW() - INTERVAL '33 days'),
('R&B Slow Jams', 'r-and-b-slow-jams', 'Smooth R&B ballads', 'images/logos/2025/01/01/r-and-b-slow-jams.jpg', 'active', NOW() - INTERVAL '32 days'),
('Hardcore Punk', 'hardcore-punk', 'Fast and furious hardcore', 'images/logos/2025/01/01/hardcore-punk.jpg', 'active', NOW() - INTERVAL '31 days'),
('Doom & Stoner', 'doom-and-stoner', 'Heavy, slow, and loud', 'images/logos/2025/01/01/doom-and-stoner.jpg', 'active', NOW() - INTERVAL '30 days'),
('Witch House', 'witch-house', 'Dark electronic atmospheres', 'images/logos/2025/01/01/witch-house.jpg', 'active', NOW() - INTERVAL '29 days'),
('Late Night Jazz', 'late-night-jazz', 'Sophisticated late night jazz', 'images/logos/2025/01/01/late-night-jazz.jpg', 'active', NOW() - INTERVAL '28 days'),
('Minimal Techno', 'minimal-techno', 'Stripped-down electronic beats', 'images/logos/2025/01/01/minimal-techno.jpg', 'active', NOW() - INTERVAL '27 days'),

-- FRIDAY
('Friday Morning Groove', 'friday-morning-groove', 'Get ready for the weekend', 'images/logos/2025/01/01/friday-morning-groove.jpg', 'active', NOW() - INTERVAL '26 days'),
('Chamber Music', 'chamber-music', 'Small ensemble classical', 'images/logos/2025/01/01/chamber-music.jpg', 'active', NOW() - INTERVAL '25 days'),
('Desert Rock', 'desert-rock', 'Stoner and desert rock', 'images/logos/2025/01/01/desert-rock.jpg', 'active', NOW() - INTERVAL '24 days'),
('Cumbia & Chicha', 'cumbia-and-chicha', 'Latin American grooves', 'images/logos/2025/01/01/cumbia-and-chicha.jpg', 'active', NOW() - INTERVAL '23 days'),
('Post-Punk Power', 'post-punk-power', 'Dark and danceable post-punk', 'images/logos/2025/01/01/post-punk-power.jpg', 'active', NOW() - INTERVAL '22 days'),
('House Music All Night', 'house-music-all-night', 'Classic house beats', 'images/logos/2025/01/01/house-music-all-night.jpg', 'active', NOW() - INTERVAL '21 days'),
('Weekend Warm-Up', 'weekend-warm-up', 'Eclectic pre-weekend mix', 'images/logos/2025/01/01/weekend-warm-up.jpg', 'active', NOW() - INTERVAL '20 days'),
('Trap & Bass', 'trap-and-bass', 'Modern trap and bass music', 'images/logos/2025/01/01/trap-and-bass.jpg', 'active', NOW() - INTERVAL '19 days'),
('Disco Fever', 'disco-fever', 'Classic disco grooves', 'images/logos/2025/01/01/disco-fever.jpg', 'active', NOW() - INTERVAL '18 days'),
('Emo Night', 'emo-night', 'Emotional hardcore and emo', 'images/logos/2025/01/01/emo-night.jpg', 'active', NOW() - INTERVAL '17 days'),
('Black Metal', 'black-metal', 'Atmospheric black metal', 'images/logos/2025/01/01/black-metal.jpg', 'active', NOW() - INTERVAL '16 days'),
('Vaporwave Dreams', 'vaporwave-dreams', 'Surreal electronic nostalgia', 'images/logos/2025/01/01/vaporwave-dreams.jpg', 'active', NOW() - INTERVAL '15 days'),
('Midnight Madness', 'midnight-madness', 'Late night party mix', 'images/logos/2025/01/01/midnight-madness.jpg', 'active', NOW() - INTERVAL '14 days'),
('Deep House', 'deep-house', 'Soulful deep house music', 'images/logos/2025/01/01/deep-house.jpg', 'active', NOW() - INTERVAL '13 days'),

-- SATURDAY
('Saturday Morning Cartoons', 'saturday-morning-cartoons', 'Fun music to start your weekend', 'images/logos/2025/01/01/saturday-morning-cartoons.jpg', 'active', NOW() - INTERVAL '12 days'),
('Opera Hour', 'opera-hour', 'Grand opera performances', 'images/logos/2025/01/01/opera-hour.jpg', 'active', NOW() - INTERVAL '11 days'),
('Surf Rock', 'surf-rock', 'Reverb-drenched guitar instrumentals', 'images/logos/2025/01/01/surf-rock.jpg', 'active', NOW() - INTERVAL '10 days'),
('Global Bass', 'global-bass', 'Bass music from around the world', 'images/logos/2025/01/01/global-bass.jpg', 'active', NOW() - INTERVAL '9 days'),
('Britpop & Beyond', 'britpop-and-beyond', '90s British rock revival', 'images/logos/2025/01/01/britpop-and-beyond.jpg', 'active', NOW() - INTERVAL '8 days'),
('Drum & Bass', 'drum-and-bass', 'High-energy jungle and D&B', 'images/logos/2025/01/01/drum-and-bass.jpg', 'active', NOW() - INTERVAL '7 days'),
('Saturday Dance Party', 'saturday-dance-party', 'Dance floor favorites', 'images/logos/2025/01/01/saturday-dance-party.jpg', 'active', NOW() - INTERVAL '6 days'),
('Lo-Fi Hip-Hop', 'lo-fi-hip-hop', 'Chill beats to relax to', 'images/logos/2025/01/01/lo-fi-hip-hop.jpg', 'active', NOW() - INTERVAL '5 days'),
('Motown & Stax', 'motown-and-stax', 'Classic soul labels', 'images/logos/2025/01/01/motown-and-stax.jpg', 'active', NOW() - INTERVAL '4 days'),
('Thrash Metal', 'thrash-metal', 'Speed and aggression', 'images/logos/2025/01/01/thrash-metal.jpg', 'active', NOW() - INTERVAL '3 days'),
('Synthwave Night', 'synthwave-night', 'Retro-futuristic synth music', 'images/logos/2025/01/01/synthwave-night.jpg', 'active', NOW() - INTERVAL '2 days'),
('Ambient Soundscapes', 'ambient-soundscapes', 'Peaceful ambient textures', 'images/logos/2025/01/01/ambient-soundscapes.jpg', 'active', NOW() - INTERVAL '1 day'),
('Late Night Beats', 'late-night-beats', 'Chill beats for late night', 'images/logos/2025/01/01/late-night-beats.jpg', 'active', NOW());
