-- Show Tags (Genre Categories)
-- Unique genre names used to categorize shows

INSERT INTO show_tags (name) VALUES
('Acoustic'),
('Afrobeat'),
('Alternative'),
('Ambient'),
('Beats'),
('Black Metal'),
('Bluegrass'),
('Blues'),
('Britpop'),
('Caribbean'),
('Classical'),
('Country'),
('Cumbia'),
('Dance'),
('Deep House'),
('Disco'),
('Doom Metal'),
('Downtempo'),
('Drum & Bass'),
('Dub/Reggae'),
('Eclectic'),
('Electronic'),
('Emo'),
('Experimental'),
('Folk'),
('Funk'),
('Garage Rock'),
('Global Bass'),
('Gospel'),
('Hardcore'),
('Hip-Hop'),
('House'),
('Indie'),
('Indie Rock'),
('Industrial'),
('Jazz'),
('Jazz Fusion'),
('Latin'),
('Lo-Fi'),
('Metal'),
('Minimal'),
('New Wave'),
('Opera'),
('Pop'),
('Pop/Rock'),
('Post-Punk'),
('Post-Rock'),
('Psychedelic'),
('Punk'),
('R&B'),
('Reggae'),
('Rock'),
('Rock/Pop'),
('Shoegaze'),
('Ska'),
('Soul'),
('Soul/Funk'),
('Soul/R&B'),
('Stoner Rock'),
('Surf Rock'),
('Synthwave'),
('Techno'),
('Thrash Metal'),
('Trap'),
('Vaporwave'),
('Variety'),
('Witch House'),
('World');
