CREATE TABLE user_metadata
  ( id SERIAL8 PRIMARY KEY UNIQUE
  , user_id INT8 NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE
  , display_name VARCHAR NOT NULL
  , full_name VARCHAR NOT NULL
  , avatar_url VARCHAR
  , is_admin BOOLEAN NOT NULL DEFAULT FALSE
  , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  , updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);