-- Show Tag Assignments
-- Links shows to their genre tags (1-3 tags per show)

INSERT INTO show_tag_assignments (show_id, tag_id)
SELECT s.id, t.id
FROM (VALUES
    -- SUNDAY (12 shows)
    ('sunday-morning-jazz', 'Jazz'),
    ('sunday-morning-jazz', 'Soul'),
    ('gospel-hour', 'Gospel'),
    ('gospel-hour', 'Soul'),
    ('gospel-hour', 'Acoustic'),
    ('world-music-passport', 'World'),
    ('world-music-passport', 'Afrobeat'),
    ('world-music-passport', 'Latin'),
    ('classical-sundays', 'Classical'),
    ('classical-sundays', 'Acoustic'),
    ('indie-mixtape', 'Indie'),
    ('indie-mixtape', 'Indie Rock'),
    ('indie-mixtape', 'Alternative'),
    ('soul-kitchen', 'Soul/R&B'),
    ('soul-kitchen', 'Funk'),
    ('acoustic-sessions', 'Folk'),
    ('acoustic-sessions', 'Acoustic'),
    ('electronic-sunday', 'Electronic'),
    ('electronic-sunday', 'Downtempo'),
    ('reggae-vibes', 'Reggae'),
    ('reggae-vibes', 'Dub/Reggae'),
    ('blues-after-dark', 'Blues'),
    ('blues-after-dark', 'Soul'),
    ('experimental-sounds', 'Experimental'),
    ('experimental-sounds', 'Ambient'),
    ('experimental-sounds', 'Electronic'),
    ('midnight-ambient', 'Ambient'),
    ('midnight-ambient', 'Electronic'),

    -- MONDAY (13 shows)
    ('monday-morning-wake-up', 'Pop'),
    ('monday-morning-wake-up', 'Rock/Pop'),
    ('coffee-and-classics', 'Classical'),
    ('folk-tales', 'Folk'),
    ('folk-tales', 'Acoustic'),
    ('folk-tales', 'Country'),
    ('midday-mix', 'Variety'),
    ('midday-mix', 'Eclectic'),
    ('latin-grooves', 'Latin'),
    ('latin-grooves', 'Cumbia'),
    ('latin-grooves', 'World'),
    ('rock-solid', 'Rock'),
    ('rock-solid', 'Metal'),
    ('drive-time', 'Eclectic'),
    ('drive-time', 'Pop/Rock'),
    ('hip-hop-fundamentals', 'Hip-Hop'),
    ('hip-hop-fundamentals', 'Beats'),
    ('jazz-lounge', 'Jazz'),
    ('jazz-lounge', 'Soul'),
    ('punk-power-hour', 'Punk'),
    ('punk-power-hour', 'Hardcore'),
    ('metal-madness', 'Metal'),
    ('metal-madness', 'Thrash Metal'),
    ('metal-madness', 'Rock'),
    ('late-night-chill', 'Downtempo'),
    ('late-night-chill', 'Electronic'),
    ('late-night-chill', 'Ambient'),
    ('graveyard-shift', 'Eclectic'),
    ('graveyard-shift', 'Ambient'),

    -- TUESDAY (13 shows)
    ('tuesday-sunrise', 'Acoustic'),
    ('tuesday-sunrise', 'Folk'),
    ('morning-brew', 'Eclectic'),
    ('morning-brew', 'Variety'),
    ('singer-songwriter-showcase', 'Folk'),
    ('singer-songwriter-showcase', 'Acoustic'),
    ('singer-songwriter-showcase', 'Indie'),
    ('world-beat', 'World'),
    ('world-beat', 'Afrobeat'),
    ('indie-rock-hour', 'Indie Rock'),
    ('indie-rock-hour', 'Alternative'),
    ('soul-stirrers', 'Soul/R&B'),
    ('soul-stirrers', 'Soul'),
    ('soul-stirrers', 'Funk'),
    ('alternative-nation', 'Alternative'),
    ('alternative-nation', 'Indie Rock'),
    ('alternative-nation', 'Rock'),
    ('electronic-evolution', 'Electronic'),
    ('electronic-evolution', 'Techno'),
    ('electronic-evolution', 'House'),
    ('country-roads', 'Country'),
    ('country-roads', 'Folk'),
    ('country-roads', 'Bluegrass'),
    ('funk-sessions', 'Funk'),
    ('funk-sessions', 'Soul'),
    ('jazz-standards', 'Jazz'),
    ('noise-and-space', 'Experimental'),
    ('noise-and-space', 'Industrial'),
    ('noise-and-space', 'Ambient'),
    ('deep-night-mix', 'Ambient'),
    ('deep-night-mix', 'Downtempo'),

    -- WEDNESDAY (13 shows)
    ('midweek-morning', 'Pop/Rock'),
    ('midweek-morning', 'Pop'),
    ('classical-interlude', 'Classical'),
    ('classical-interlude', 'Opera'),
    ('folk-underground', 'Folk'),
    ('folk-underground', 'Bluegrass'),
    ('folk-underground', 'Acoustic'),
    ('lunch-hour-favorites', 'Variety'),
    ('lunch-hour-favorites', 'Pop'),
    ('afrobeat-express', 'Afrobeat'),
    ('afrobeat-express', 'World'),
    ('afrobeat-express', 'Funk'),
    ('psychedelic-journey', 'Psychedelic'),
    ('psychedelic-journey', 'Rock'),
    ('psychedelic-journey', 'Experimental'),
    ('hip-hop-heritage', 'Hip-Hop'),
    ('hip-hop-heritage', 'Beats'),
    ('hip-hop-heritage', 'Funk'),
    ('dub-vibrations', 'Dub/Reggae'),
    ('dub-vibrations', 'Reggae'),
    ('dub-vibrations', 'Electronic'),
    ('shoegaze-and-dream-pop', 'Shoegaze'),
    ('shoegaze-and-dream-pop', 'Indie'),
    ('shoegaze-and-dream-pop', 'Alternative'),
    ('jazz-fusion', 'Jazz Fusion'),
    ('jazz-fusion', 'Jazz'),
    ('jazz-fusion', 'Funk'),
    ('post-rock-horizons', 'Post-Rock'),
    ('post-rock-horizons', 'Ambient'),
    ('post-rock-horizons', 'Experimental'),
    ('industrial-underground', 'Industrial'),
    ('industrial-underground', 'Electronic'),
    ('night-drones', 'Ambient'),
    ('night-drones', 'Experimental'),

    -- THURSDAY (14 shows)
    ('thursday-wake-up-call', 'Rock/Pop'),
    ('thursday-wake-up-call', 'Pop'),
    ('baroque-and-beyond', 'Classical'),
    ('bluegrass-and-old-time', 'Bluegrass'),
    ('bluegrass-and-old-time', 'Folk'),
    ('bluegrass-and-old-time', 'Country'),
    ('tropical-sounds', 'Caribbean'),
    ('tropical-sounds', 'Reggae'),
    ('tropical-sounds', 'World'),
    ('garage-rock-revival', 'Garage Rock'),
    ('garage-rock-revival', 'Punk'),
    ('garage-rock-revival', 'Rock'),
    ('new-wave-nostalgia', 'New Wave'),
    ('new-wave-nostalgia', 'Synthwave'),
    ('new-wave-nostalgia', 'Post-Punk'),
    ('techno-territory', 'Techno'),
    ('techno-territory', 'Electronic'),
    ('ska-and-rocksteady', 'Ska'),
    ('ska-and-rocksteady', 'Reggae'),
    ('r-and-b-slow-jams', 'R&B'),
    ('r-and-b-slow-jams', 'Soul'),
    ('r-and-b-slow-jams', 'Soul/R&B'),
    ('hardcore-punk', 'Hardcore'),
    ('hardcore-punk', 'Punk'),
    ('doom-and-stoner', 'Doom Metal'),
    ('doom-and-stoner', 'Stoner Rock'),
    ('doom-and-stoner', 'Metal'),
    ('witch-house', 'Witch House'),
    ('witch-house', 'Electronic'),
    ('witch-house', 'Experimental'),
    ('late-night-jazz', 'Jazz'),
    ('late-night-jazz', 'Soul'),
    ('minimal-techno', 'Minimal'),
    ('minimal-techno', 'Techno'),
    ('minimal-techno', 'Electronic'),

    -- FRIDAY (14 shows)
    ('friday-morning-groove', 'Soul/Funk'),
    ('friday-morning-groove', 'Funk'),
    ('friday-morning-groove', 'Soul'),
    ('chamber-music', 'Classical'),
    ('chamber-music', 'Acoustic'),
    ('desert-rock', 'Stoner Rock'),
    ('desert-rock', 'Psychedelic'),
    ('desert-rock', 'Rock'),
    ('cumbia-and-chicha', 'Cumbia'),
    ('cumbia-and-chicha', 'Latin'),
    ('cumbia-and-chicha', 'World'),
    ('post-punk-power', 'Post-Punk'),
    ('post-punk-power', 'New Wave'),
    ('post-punk-power', 'Industrial'),
    ('house-music-all-night', 'House'),
    ('house-music-all-night', 'Electronic'),
    ('house-music-all-night', 'Dance'),
    ('weekend-warm-up', 'Variety'),
    ('weekend-warm-up', 'Eclectic'),
    ('trap-and-bass', 'Trap'),
    ('trap-and-bass', 'Hip-Hop'),
    ('trap-and-bass', 'Electronic'),
    ('disco-fever', 'Disco'),
    ('disco-fever', 'Dance'),
    ('disco-fever', 'Funk'),
    ('emo-night', 'Emo'),
    ('emo-night', 'Punk'),
    ('emo-night', 'Alternative'),
    ('black-metal', 'Black Metal'),
    ('black-metal', 'Metal'),
    ('vaporwave-dreams', 'Vaporwave'),
    ('vaporwave-dreams', 'Electronic'),
    ('vaporwave-dreams', 'Synthwave'),
    ('midnight-madness', 'Eclectic'),
    ('midnight-madness', 'Dance'),
    ('midnight-madness', 'Electronic'),
    ('deep-house', 'Deep House'),
    ('deep-house', 'House'),
    ('deep-house', 'Electronic'),

    -- SATURDAY (13 shows)
    ('saturday-morning-cartoons', 'Pop'),
    ('saturday-morning-cartoons', 'Variety'),
    ('opera-hour', 'Opera'),
    ('opera-hour', 'Classical'),
    ('surf-rock', 'Surf Rock'),
    ('surf-rock', 'Rock'),
    ('surf-rock', 'Garage Rock'),
    ('global-bass', 'Global Bass'),
    ('global-bass', 'Electronic'),
    ('global-bass', 'World'),
    ('britpop-and-beyond', 'Britpop'),
    ('britpop-and-beyond', 'Indie Rock'),
    ('britpop-and-beyond', 'Alternative'),
    ('drum-and-bass', 'Drum & Bass'),
    ('drum-and-bass', 'Electronic'),
    ('saturday-dance-party', 'Dance'),
    ('saturday-dance-party', 'House'),
    ('saturday-dance-party', 'Disco'),
    ('lo-fi-hip-hop', 'Lo-Fi'),
    ('lo-fi-hip-hop', 'Hip-Hop'),
    ('lo-fi-hip-hop', 'Beats'),
    ('motown-and-stax', 'Soul'),
    ('motown-and-stax', 'Soul/R&B'),
    ('motown-and-stax', 'Funk'),
    ('thrash-metal', 'Thrash Metal'),
    ('thrash-metal', 'Metal'),
    ('thrash-metal', 'Hardcore'),
    ('synthwave-night', 'Synthwave'),
    ('synthwave-night', 'Electronic'),
    ('synthwave-night', 'New Wave'),
    ('ambient-soundscapes', 'Ambient'),
    ('ambient-soundscapes', 'Experimental'),
    ('late-night-beats', 'Beats'),
    ('late-night-beats', 'Lo-Fi'),
    ('late-night-beats', 'Downtempo')
) AS tag_data(slug, tag_name)
JOIN shows s ON s.slug = tag_data.slug
JOIN show_tags t ON t.name = tag_data.tag_name;
