-- Host User Metadata
-- Themed display names and real-sounding full names for each host

INSERT INTO user_metadata (user_id, display_name, full_name, avatar_url, user_role)
SELECT
    u.id,
    CASE s.slug
        -- SUNDAY
        WHEN 'sunday-morning-jazz' THEN 'Smooth Sullivan'
        WHEN 'gospel-hour' THEN 'Sister Joy'
        WHEN 'world-music-passport' THEN 'DJ Wanderlust'
        WHEN 'classical-sundays' THEN 'Maestro Chen'
        WHEN 'indie-mixtape' THEN 'Cassette Kid'
        WHEN 'soul-kitchen' THEN 'Chef Groove'
        WHEN 'acoustic-sessions' THEN 'Willow Hart'
        WHEN 'electronic-sunday' THEN 'Circuit Breaker'
        WHEN 'reggae-vibes' THEN 'Irie Lion'
        WHEN 'blues-after-dark' THEN 'Midnight Willie'
        WHEN 'experimental-sounds' THEN 'The Sound Scientist'
        WHEN 'midnight-ambient' THEN 'Lunar Drift'

        -- MONDAY
        WHEN 'monday-morning-wake-up' THEN 'Sunrise Sam'
        WHEN 'coffee-and-classics' THEN 'Morning Mozart'
        WHEN 'folk-tales' THEN 'Storyteller Sarah'
        WHEN 'midday-mix' THEN 'DJ Kaleidoscope'
        WHEN 'latin-grooves' THEN 'Ritmo Rico'
        WHEN 'rock-solid' THEN 'Rockin'' Ricky'
        WHEN 'drive-time' THEN 'Highway Holly'
        WHEN 'hip-hop-fundamentals' THEN 'DJ Knowledge'
        WHEN 'jazz-lounge' THEN 'Marcus the Velvet Voice'
        WHEN 'punk-power-hour' THEN 'Spike Voltage'
        WHEN 'metal-madness' THEN 'Thor the Destroyer'
        WHEN 'late-night-chill' THEN 'Luna Waves'
        WHEN 'graveyard-shift' THEN 'Nocturnal Nick'

        -- TUESDAY
        WHEN 'tuesday-sunrise' THEN 'Dawn Melody'
        WHEN 'morning-brew' THEN 'Java Jones'
        WHEN 'singer-songwriter-showcase' THEN 'Lyric Lou'
        WHEN 'world-beat' THEN 'Rhythm Runner'
        WHEN 'indie-rock-hour' THEN 'Garage Gary'
        WHEN 'soul-stirrers' THEN 'Deep Soul Davis'
        WHEN 'alternative-nation' THEN 'Alt Alex'
        WHEN 'electronic-evolution' THEN 'Synth Prophet'
        WHEN 'country-roads' THEN 'Honky Tonk Hannah'
        WHEN 'funk-sessions' THEN 'Funky Fred'
        WHEN 'jazz-standards' THEN 'Classic Coltrane'
        WHEN 'noise-and-space' THEN 'Static Storm'
        WHEN 'deep-night-mix' THEN 'Shadow Spinner'

        -- WEDNESDAY
        WHEN 'midweek-morning' THEN 'Hump Day Hero'
        WHEN 'classical-interlude' THEN 'Violina Virtuoso'
        WHEN 'folk-underground' THEN 'Woody Wanderer'
        WHEN 'lunch-hour-favorites' THEN 'Midday Mike'
        WHEN 'afrobeat-express' THEN 'Fela Junior'
        WHEN 'psychedelic-journey' THEN 'Cosmic Carl'
        WHEN 'hip-hop-heritage' THEN 'Old School O''Shea'
        WHEN 'dub-vibrations' THEN 'Bass Commander'
        WHEN 'shoegaze-and-dream-pop' THEN 'Reverb Rachel'
        WHEN 'jazz-fusion' THEN 'Fusion Phil'
        WHEN 'post-rock-horizons' THEN 'Epic Evan'
        WHEN 'industrial-underground' THEN 'Factory Floor Fiona'
        WHEN 'night-drones' THEN 'Drone Master D'

        -- THURSDAY
        WHEN 'thursday-wake-up-call' THEN 'Almost Friday Ali'
        WHEN 'baroque-and-beyond' THEN 'Baroque Baron'
        WHEN 'bluegrass-and-old-time' THEN 'Banjo Betty'
        WHEN 'tropical-sounds' THEN 'Island Izzy'
        WHEN 'garage-rock-revival' THEN 'Fuzz Face'
        WHEN 'new-wave-nostalgia' THEN 'Neon Nancy'
        WHEN 'techno-territory' THEN 'Berlin Bob'
        WHEN 'ska-and-rocksteady' THEN 'Skank Master Steve'
        WHEN 'r-and-b-slow-jams' THEN 'Smooth Operator Sade'
        WHEN 'hardcore-punk' THEN 'Hardcore Harry'
        WHEN 'doom-and-stoner' THEN 'Riff Lord Randy'
        WHEN 'witch-house' THEN 'Hex Hannah'
        WHEN 'late-night-jazz' THEN 'After Hours Marcus'
        WHEN 'minimal-techno' THEN 'Minimal Max'

        -- FRIDAY
        WHEN 'friday-morning-groove' THEN 'Groove Master G'
        WHEN 'chamber-music' THEN 'Quartet Quinn'
        WHEN 'desert-rock' THEN 'Desert Dan'
        WHEN 'cumbia-and-chicha' THEN 'Cumbia Carlos'
        WHEN 'post-punk-power' THEN 'Dark Wave Dave'
        WHEN 'house-music-all-night' THEN 'House Head Henry'
        WHEN 'weekend-warm-up' THEN 'Party Starter Pat'
        WHEN 'trap-and-bass' THEN '808 Tyler'
        WHEN 'disco-fever' THEN 'Disco Donna'
        WHEN 'emo-night' THEN 'Emotional Eric'
        WHEN 'black-metal' THEN 'Frost Fenrir'
        WHEN 'vaporwave-dreams' THEN 'Aesthetic Andy'
        WHEN 'midnight-madness' THEN 'Wild Card Wanda'
        WHEN 'deep-house' THEN 'Deep Space Diana'

        -- SATURDAY
        WHEN 'saturday-morning-cartoons' THEN 'Captain Cartoon'
        WHEN 'opera-hour' THEN 'Opera Oscar'
        WHEN 'surf-rock' THEN 'Wave Rider Wendy'
        WHEN 'global-bass' THEN 'Bassline Boris'
        WHEN 'britpop-and-beyond' THEN 'Britpop Barry'
        WHEN 'drum-and-bass' THEN 'Jungle Jane'
        WHEN 'saturday-dance-party' THEN 'Dance Floor Danny'
        WHEN 'lo-fi-hip-hop' THEN 'Chill Beats Charlie'
        WHEN 'motown-and-stax' THEN 'Motown Mary'
        WHEN 'thrash-metal' THEN 'Thrash Tommy'
        WHEN 'synthwave-night' THEN 'Retro Racer Rita'
        WHEN 'ambient-soundscapes' THEN 'Ambient Aurora'
        WHEN 'late-night-beats' THEN 'Beat Maker Ben'

        ELSE INITCAP(REPLACE(REPLACE(u.email, 'host-', ''), '@kpbj.fm', ''))
    END as display_name,
    CASE s.slug
        -- Generate matching full names that sound real
        WHEN 'sunday-morning-jazz' THEN 'Marcus Sullivan'
        WHEN 'gospel-hour' THEN 'Joyce Williams'
        WHEN 'world-music-passport' THEN 'Amara Okafor'
        WHEN 'classical-sundays' THEN 'Li Chen'
        WHEN 'indie-mixtape' THEN 'Alex Thompson'
        WHEN 'soul-kitchen' THEN 'Jerome Washington'
        WHEN 'acoustic-sessions' THEN 'Willow Hart'
        WHEN 'electronic-sunday' THEN 'Tyler Mitchell'
        WHEN 'reggae-vibes' THEN 'Winston Clarke'
        WHEN 'blues-after-dark' THEN 'Willie Johnson'
        WHEN 'experimental-sounds' THEN 'Dr. Adrian Pierce'
        WHEN 'midnight-ambient' THEN 'Luna Castellanos'
        WHEN 'monday-morning-wake-up' THEN 'Samantha Rodriguez'
        WHEN 'coffee-and-classics' THEN 'Wolfgang Bauer'
        WHEN 'folk-tales' THEN 'Sarah Jennings'
        WHEN 'midday-mix' THEN 'Kai Anderson'
        WHEN 'latin-grooves' THEN 'Ricardo Gonzalez'
        WHEN 'rock-solid' THEN 'Rick Stone'
        WHEN 'drive-time' THEN 'Holly Martinez'
        WHEN 'hip-hop-fundamentals' THEN 'Kenneth Wright'
        WHEN 'jazz-lounge' THEN 'Marcus Williams'
        WHEN 'punk-power-hour' THEN 'Spike Ramirez'
        WHEN 'metal-madness' THEN 'Thor Magnusson'
        WHEN 'late-night-chill' THEN 'Luna Chen'
        WHEN 'graveyard-shift' THEN 'Nick Torres'
        WHEN 'tuesday-sunrise' THEN 'Dawn Melody'
        WHEN 'morning-brew' THEN 'James Jones'
        WHEN 'singer-songwriter-showcase' THEN 'Louise Carter'
        WHEN 'world-beat' THEN 'Kwame Mensah'
        WHEN 'indie-rock-hour' THEN 'Gary Foster'
        WHEN 'soul-stirrers' THEN 'David Davis'
        WHEN 'alternative-nation' THEN 'Alex Morgan'
        WHEN 'electronic-evolution' THEN 'Elijah Prophet'
        WHEN 'country-roads' THEN 'Hannah Brooks'
        WHEN 'funk-sessions' THEN 'Frederick Brown'
        WHEN 'jazz-standards' THEN 'Miles Jefferson'
        WHEN 'noise-and-space' THEN 'Storm Rivers'
        WHEN 'deep-night-mix' THEN 'Shadow Kim'
        WHEN 'midweek-morning' THEN 'Hero Patel'
        WHEN 'classical-interlude' THEN 'Violina Rossi'
        WHEN 'folk-underground' THEN 'Woody Sanders'
        WHEN 'lunch-hour-favorites' THEN 'Michael Peterson'
        WHEN 'afrobeat-express' THEN 'Segun Adeyemi'
        WHEN 'psychedelic-journey' THEN 'Carl Morrison'
        WHEN 'hip-hop-heritage' THEN 'O''Shea Jackson'
        WHEN 'dub-vibrations' THEN 'Commander Bass'
        WHEN 'shoegaze-and-dream-pop' THEN 'Rachel Summers'
        WHEN 'jazz-fusion' THEN 'Phil Henderson'
        WHEN 'post-rock-horizons' THEN 'Evan Roberts'
        WHEN 'industrial-underground' THEN 'Fiona Steel'
        WHEN 'night-drones' THEN 'Darius Moon'
        WHEN 'thursday-wake-up-call' THEN 'Ali Hassan'
        WHEN 'baroque-and-beyond' THEN 'Baron Von Schmidt'
        WHEN 'bluegrass-and-old-time' THEN 'Betty Monroe'
        WHEN 'tropical-sounds' THEN 'Isabella Cruz'
        WHEN 'garage-rock-revival' THEN 'Fuzz Patterson'
        WHEN 'new-wave-nostalgia' THEN 'Nancy Zhang'
        WHEN 'techno-territory' THEN 'Bob Mueller'
        WHEN 'ska-and-rocksteady' THEN 'Steve Campbell'
        WHEN 'r-and-b-slow-jams' THEN 'Sade Johnson'
        WHEN 'hardcore-punk' THEN 'Harry Collins'
        WHEN 'doom-and-stoner' THEN 'Randy Pike'
        WHEN 'witch-house' THEN 'Hannah Black'
        WHEN 'late-night-jazz' THEN 'Marcus Williams'
        WHEN 'minimal-techno' THEN 'Max Klein'
        WHEN 'friday-morning-groove' THEN 'Gerald Green'
        WHEN 'chamber-music' THEN 'Quinn Abbott'
        WHEN 'desert-rock' THEN 'Daniel Coyote'
        WHEN 'cumbia-and-chicha' THEN 'Carlos Vargas'
        WHEN 'post-punk-power' THEN 'David Curtis'
        WHEN 'house-music-all-night' THEN 'Henry Walker'
        WHEN 'weekend-warm-up' THEN 'Patricia Lee'
        WHEN 'trap-and-bass' THEN 'Tyler Young'
        WHEN 'disco-fever' THEN 'Donna Summer'
        WHEN 'emo-night' THEN 'Eric Heartbreak'
        WHEN 'black-metal' THEN 'Fenrir Frost'
        WHEN 'vaporwave-dreams' THEN 'Andy Digital'
        WHEN 'midnight-madness' THEN 'Wanda Wild'
        WHEN 'deep-house' THEN 'Diana Prince'
        WHEN 'saturday-morning-cartoons' THEN 'Captain Carl'
        WHEN 'opera-hour' THEN 'Oscar Pavarotti'
        WHEN 'surf-rock' THEN 'Wendy Mavericks'
        WHEN 'global-bass' THEN 'Boris Petrov'
        WHEN 'britpop-and-beyond' THEN 'Barry Gallagher'
        WHEN 'drum-and-bass' THEN 'Jane Jungler'
        WHEN 'saturday-dance-party' THEN 'Danny Beats'
        WHEN 'lo-fi-hip-hop' THEN 'Charlie Vibes'
        WHEN 'motown-and-stax' THEN 'Mary Ross'
        WHEN 'thrash-metal' THEN 'Tommy Mayhem'
        WHEN 'synthwave-night' THEN 'Rita Neon'
        WHEN 'ambient-soundscapes' THEN 'Aurora Fields'
        WHEN 'late-night-beats' THEN 'Benjamin Producer'
        ELSE INITCAP(REPLACE(REPLACE(REPLACE(u.email, 'host-', ''), '@kpbj.fm', ''), '-', ' '))
    END as full_name,
    -- Avatar URLs for hosts that have avatar images
    CASE s.slug
        WHEN 'sunday-morning-jazz' THEN 'images/2025/01/01/avatars/smooth-sullivan.jpg'
        WHEN 'gospel-hour' THEN 'images/2025/01/01/avatars/sister-joy.jpg'
        WHEN 'world-music-passport' THEN 'images/2025/01/01/avatars/dj-wanderlust.jpg'
        WHEN 'classical-sundays' THEN 'images/2025/01/01/avatars/maestro-chen.jpg'
        WHEN 'indie-mixtape' THEN 'images/2025/01/01/avatars/cassette-kid.jpg'
        WHEN 'soul-kitchen' THEN 'images/2025/01/01/avatars/chef-groove.jpg'
        WHEN 'acoustic-sessions' THEN 'images/2025/01/01/avatars/willow-hart.jpg'
        WHEN 'electronic-sunday' THEN 'images/2025/01/01/avatars/circuit-breaker.jpg'
        WHEN 'reggae-vibes' THEN 'images/2025/01/01/avatars/irie-lion.jpg'
        WHEN 'blues-after-dark' THEN 'images/2025/01/01/avatars/midnight-willie.jpg'
        WHEN 'experimental-sounds' THEN 'images/2025/01/01/avatars/the-sound-scientist.jpg'
        WHEN 'midnight-ambient' THEN 'images/2025/01/01/avatars/lunar-drift.jpg'
        WHEN 'monday-morning-wake-up' THEN 'images/2025/01/01/avatars/sunrise-sam.jpg'
        WHEN 'hip-hop-fundamentals' THEN 'images/2025/01/01/avatars/dj-knowledge.jpg'
        WHEN 'punk-power-hour' THEN 'images/2025/01/01/avatars/spike-voltage.jpg'
        WHEN 'metal-madness' THEN 'images/2025/01/01/avatars/thor-the-destroyer.jpg'
        WHEN 'late-night-chill' THEN 'images/2025/01/01/avatars/luna-waves.jpg'
        WHEN 'psychedelic-journey' THEN 'images/2025/01/01/avatars/cosmic-carl.jpg'
        WHEN 'dub-vibrations' THEN 'images/2025/01/01/avatars/bass-commander.jpg'
        WHEN 'shoegaze-and-dream-pop' THEN 'images/2025/01/01/avatars/reverb-rachel.jpg'
        WHEN 'new-wave-nostalgia' THEN 'images/2025/01/01/avatars/neon-nancy.jpg'
        WHEN 'techno-territory' THEN 'images/2025/01/01/avatars/berlin-bob.jpg'
        WHEN 'witch-house' THEN 'images/2025/01/01/avatars/hex-hannah.jpg'
        WHEN 'disco-fever' THEN 'images/2025/01/01/avatars/disco-donna.jpg'
        WHEN 'black-metal' THEN 'images/2025/01/01/avatars/frost-fenrir.jpg'
        WHEN 'vaporwave-dreams' THEN 'images/2025/01/01/avatars/aesthetic-andy.jpg'
        WHEN 'drum-and-bass' THEN 'images/2025/01/01/avatars/jungle-jane.jpg'
        WHEN 'synthwave-night' THEN 'images/2025/01/01/avatars/retro-racer-rita.jpg'
        WHEN 'ambient-soundscapes' THEN 'images/2025/01/01/avatars/ambient-aurora.jpg'
        ELSE NULL
    END as avatar_url,
    'Host' as user_role
FROM users u
JOIN shows s ON u.email = 'host-' || s.slug || '@kpbj.fm';
