#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# nixos-setup.sh — Post-provision setup for NixOS droplets
# ──────────────────────────────────────────────────────────────
#
# Completes NixOS setup after Terraform creates a fresh droplet.
# nixos-infect runs automatically via user_data and reboots the
# droplet into NixOS. This script waits for that reboot, then:
#
#   1. Polls SSH until the droplet is running NixOS
#   2. Copies hardware-configuration.nix from the droplet
#   3. Retrieves the host's age public key for SOPS encryption
#   4. Prints next steps
#
# Usage:
#   ./scripts/nixos-setup.sh <host> <environment>
#     host:        SSH target (e.g., root@<ip>)
#     environment: staging or prod
#
# Prerequisites:
#   - Droplet created via `just tf-apply`
#   - SSH key matches one in terraform/variables.tf
#   - ssh-to-age installed (provided via nix develop)
# ──────────────────────────────────────────────────────────────

set -euo pipefail

HOST="${1:?Usage: nixos-setup.sh <host> <environment>}"
ENV="${2:?Usage: nixos-setup.sh <host> <environment>}"

if [[ "$ENV" != "staging" && "$ENV" != "prod" ]]; then
  echo "ERROR: environment must be 'staging' or 'prod'"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HARDWARE_NIX="${SCRIPT_DIR}/nixos/hardware-digitalocean.nix"
NETWORKING_NIX="${SCRIPT_DIR}/nixos/networking-${ENV}.nix"
TIMEOUT=600  # 10 minutes
INTERVAL=15

echo "═══════════════════════════════════════════════════════"
echo "  NixOS setup for ${ENV}"
echo "  Host: ${HOST}"
echo "═══════════════════════════════════════════════════════"
echo ""

# ── Step 1: Wait for NixOS ────────────────────────────────────

echo "── Waiting for nixos-infect to complete (up to ${TIMEOUT}s) ──"
echo "   The droplet will reboot after conversion. This is normal."
echo ""

elapsed=0
while [ "$elapsed" -lt "$TIMEOUT" ]; do
  if ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes \
    "$HOST" "test -f /etc/NIXOS" 2>/dev/null; then
    echo "   NixOS detected!"
    break
  fi

  echo "   Waiting... (${elapsed}s / ${TIMEOUT}s)"
  sleep "$INTERVAL"
  elapsed=$((elapsed + INTERVAL))
done

if [ "$elapsed" -ge "$TIMEOUT" ]; then
  echo "ERROR: Timed out waiting for NixOS. Check the droplet console."
  echo "  - nixos-infect log: /tmp/nixos-infect.log"
  exit 1
fi

echo ""

# ── Step 2: Retrieve hardware configuration ───────────────────

echo "── Retrieving hardware-configuration.nix ──"

scp -o StrictHostKeyChecking=no \
  "${HOST}:/etc/nixos/hardware-configuration.nix" \
  "${HARDWARE_NIX}"

echo "   Saved to: nixos/hardware-digitalocean.nix"
echo ""

# ── Step 3: Retrieve networking configuration ──────────────────

echo "── Retrieving networking.nix (generated by nixos-infect) ──"

scp -o StrictHostKeyChecking=no \
  "${HOST}:/etc/nixos/networking.nix" \
  "${NETWORKING_NIX}"

echo "   Saved to: nixos/networking-${ENV}.nix"
echo "   Contains static IP config for this specific droplet."
echo ""

# ── Step 4: Get host age key for SOPS ──────────────────────────

echo "── Retrieving SSH host key for SOPS age encryption ──"

HOST_AGE_KEY=$(ssh-keyscan -t ed25519 "${HOST#*@}" 2>/dev/null | ssh-to-age)

if [ -z "$HOST_AGE_KEY" ]; then
  echo "   ERROR: Could not retrieve host age key."
  echo "   Ensure the host has an ed25519 SSH key and ssh-to-age is installed."
  exit 1
fi

echo "   Host age key: ${HOST_AGE_KEY}"
echo ""
echo "   Add this key to .sops.yaml under &vps_stream_${ENV}"
echo "   Then run: sops updatekeys secrets/${ENV}-streaming.yaml"
echo ""

# ── Done ──────────────────────────────────────────────────────

echo "═══════════════════════════════════════════════════════"
echo "  Setup complete!"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Review nixos/hardware-digitalocean.nix"
echo "  2. Add host age key to .sops.yaml (vps_stream_${ENV})"
echo "  3. Create secrets: sops secrets/${ENV}-streaming.yaml"
echo "  4. Update keys:    sops updatekeys secrets/${ENV}-streaming.yaml"
echo "  5. Deploy:         just nixos-deploy-${ENV}"
echo "  6. Verify: curl -I https://$([ "$ENV" = "prod" ] && echo "stream.kpbj.fm" || echo "stream.staging.kpbj.fm")/stream"
