db_password: ENC[AES256_GCM,data:6mzJiGSUcFbmN5236GsH3cXjTOo=,iv:E3PgLZZb7yUpH2m8QiC2RwZ9NW4KpA5lET1pnR8gEhg=,tag:wX2S8jTje7jhcXOMGWKrAw==,type:str]
smtp_password: ENC[AES256_GCM,data:wpxLZYSEhponHeQ7eMRG+0gGQw==,iv:usB3pSfQPQL8IOUYnHdEffACE7xjPq0gFXJUsCP0A+I=,tag:mZ9iNCbkarpj6Md9xGuMRw==,type:str]
aws_access_key_id: ENC[AES256_GCM,data:fcPX/jzybuO6hHKOzXViJCU6XlV6o6T2FcuKnIkG4mTB7dKsczxC/JiredOTg8v0KP9IXqxC,iv:yuJUnLtf6H3cjQKvuNh+JObIAfqck9/MXBDp8Cjg0f0=,tag:YI+ZRVjJrBYXL7UsEMrCbQ==,type:str]
aws_secret_access_key: ENC[AES256_GCM,data:VbXNVPsLw3KMzp6ESvbX7UYpzDofe0Gn3iAwMGcdv+8zTFEgkytr5sLmZf3u5A1UDxuJxlhb9TYklIsoPDvTpBJUVw6CeJu2FxXK,iv:NUURwGtVeBF1I+u+bgFFD9JZS+gXoW2vPWt0W+Q72xE=,tag:eM2ejIX9x4MFme3Sohe6hw==,type:str]
google_analytics_gtag: ENC[AES256_GCM,data:3moz29qnL2rUydxk,iv:qnAsnElTqQaKwYv7gbQuK8hy4Qjjf+/2/o9DsnI6CV8=,tag:dXxOVs4IUrJmy36E2T0a/A==,type:str]
sops:
    age:
        - recipient: age1hm87e69thh5c4glk9w2gn2dn3mhexe7cen3c57upfg9zech9qe9sz0ha4j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb2IwSVBxaVJvTTF1dXFh
            ZTRzL2d2emNiejgvMmJLV3NiOWRnVlBBNVNFCkNMWmZvaEMwbDdzZnZ6RHZZcjhH
            V3c3OHAyMFV3M2l3MjNqMkhZL3plVFUKLS0tIE5wcEErYkhrRUxjTm1rdSs0czRz
            dUxQTkRKWXllVExFZUdjWklZSFQvS0kK6q0hLJ+c6Ih8VKvo/gRJQvuM6Ej3nbct
            VHojARCS+Szjue1ju75IvgvHytBHb9SjS0Gpwuvfq4cNZc4w2/ch1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h9eclrfude5fkzvt0v7sjyhfsu5f839xw0wwh29lrptq70mfvgescqng6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV2EvQTVycHlBMldDQnFC
            Wnh0NnR3S3dhRWNJeWdaWGdNNzZZMnBHRFhzCjZqMldtcXJjK1FPaFFzeFZKK2lH
            OXgraXkzNjJNMkF3aElLWVZjditjZlUKLS0tIFhSaUJ3dTNRUSsxbG00dXd2Tnc2
            ZHQ2b0RhaXY5cHp5N3BTZFA2OUI5QzgKqakD2kwjGFgD1mB+IYbQrVm2hu4CKZ5R
            PmJx0XoucFHuSs6KHaHBRU9CvZ6ZlSzL1Y79W17fEaDVzkzkaCz/GA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1esadyxrm9kjt25jlg9y0mmp8u75mh05pncxxd8csl7z6dsycy3pszhrh35
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cVhkM08vZG9RR1RIcWlw
            eVZSZ0ZRQlNDeE8wWm9YNVZZWlA3QkpyZkd3CkVkRlRNK3dRdndJOXZpMzJ4NEg3
            UmV3ZmFiTGxNQlEwa0cxanNrcWNEVlUKLS0tIHhXYnVjcGdYOEdLZnhLeEFiditB
            dko5RHNSRjkrN2dGOFB5ZWhNTFhqTUUKMh/OGpIJnM2rxKe0eoN71T389FtQbyFM
            g5NUJc0jFfxpqgUsOEfIf7Hgv8E9AuITHcuUW/B6i3x9CfPqjyZMAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19nrffgaz7xtwk9jlznxt2003znguk7jvewz6s3clkzjxe0m07qlsjfkwet
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbE0vamgvQUNuSUVCVVdx
            NE0ydS84d1IvOFhHOS9OMDVIZmJodjB3ejFBClR4MHJnOENqZlZZL1NuMmxpN3kx
            OTNycjQwd0E4RjUyWmRaMjMwUXQ1VTAKLS0tIDF2dzVLVG9SdXlpbFE0L3Q5UDRW
            amNMdG8xVU9hcWNTdXZYZDZXNXlsbGcK0LwcOCCvwgYScQnFfbThExUHfbfIgW6w
            I/Z3r2UISVjX5QNcFXDKrQCZ2gqr0YgZ+IPpquq5n4UOZEgX3NV6PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T02:10:26Z"
    mac: ENC[AES256_GCM,data:ojj29ND13e4SJzod27dGnxDDIowalI6H159VWeXA/tkgtWG7TwV+DstZ1QE2Ll4iXcKJv/r2YIErUL8DoQ1cj+qMkG940b+B7syyZHSJsyERYJzf1my7lY+v4I9oyQsx7hgyt7qjIavwTAJXdQcBSBuMMzrR1NftcKenvaJzjBY=,iv:ERmwGOe6DoE56H1GvxrPzsvtHCWjt0y1RTfROxeUEJE=,tag:pTLZbxcLOX35ecdHCdlD5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
