icecast_admin_password: ENC[AES256_GCM,data:4J2x8GfwtB2uT1IcQ4L0A7CjpXUzTSbSEc5zn8G3MSM=,iv:SM53u/48Nxd9SL4a/2CHH+qJyHAoAkykGRd/pihqQv0=,tag:vUhx1XIzUnJMwHIinlsWBQ==,type:str]
icecast_relay_password: ENC[AES256_GCM,data:jaoyiAmyXGnwoDq18rwS6P6wzP7Tbq2QXJqs4kPpXyI=,iv:tTTWfR7HXZWXco4ad3UrAIxmJebGHGR7Uw4AUo/AV50=,tag:gW7Vuw9CThiYS+K7vm/x6A==,type:str]
icecast_password: ENC[AES256_GCM,data:T0q6bisr+lZyJOuyJXRgCV21PxRbqCsXNJ7k5CMGxbo=,iv:kzbtmmUIwYoRQ/L0ITPSUmJH8xNrCrSNQ/YDPmM3Uhc=,tag:mUxQreP00WlH1F9vRLmzTg==,type:str]
webhook_secret: ENC[AES256_GCM,data:w51F2WIIFe0WZgTv9n574sfftKrSVsDSsyRtd4EtTk4=,iv:pn0LJci7nOibqv7cCwufVZk71u3FBkjFYsdp4hhMcY8=,tag:6eYf2CRd7SLEfDTDLlhjAA==,type:str]
playout_secret: ENC[AES256_GCM,data:pQBaoRlVNjrEewSGVngmZ2n3UoYRj5t7gpiV0vMtuxw=,iv:OOwf/eQ4mAFwWpL02b/pJKBw/cG3X39tMWtLkd2j7fI=,tag:3cXuw6tNBxWa3LrXjEMo3w==,type:str]
sops:
    age:
        - recipient: age1hm87e69thh5c4glk9w2gn2dn3mhexe7cen3c57upfg9zech9qe9sz0ha4j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVXlPT3F4UFlESE9PMmRv
            QWVQUVRRek5XQUYrc2ZSTDVia3M5eE5BYVJRCmJPV3EzMlUrcDRtdUdhUmJaRHhz
            QytyaFJZbUNEODQraTVoSVJadFh2eVEKLS0tIHpRUjB4cjdoVkJlNDFWOVBzQ1BQ
            d2c0TkV1Nm9kb2EyaDJyc20rb0VRTTAKLC3V4PdoCAmVKBGtYQ/I6xFjbfBcewo8
            tuN2lUFrEW7o/KobEqX+zehHMNYxLHP25usT1huqSTtAKsDy0nGpKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h9eclrfude5fkzvt0v7sjyhfsu5f839xw0wwh29lrptq70mfvgescqng6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud01HeUFmZTdrLzhPWnpP
            d2NncmNSV0tTY1hEUXV3YUpuZExnVytodVcwClBKWnMwbCtYVjZXRS81VktPbTJ0
            UkhoUHBYdUFnZVJpOTRwV0hUQm9sZE0KLS0tIGh0SWdPMlJiOC9sU2dORGhPbE55
            cmxXOWNmcEd5b2MxTmRWVGF2dHMvcUkKRPxLo8Wfcobkm4sh2BkQCkIJsPOuKcv9
            ++cxWcEzg2pgOThVzoy+AVPcEMyPIXswBiozaF7T0o9JcE6X+SAyyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1esadyxrm9kjt25jlg9y0mmp8u75mh05pncxxd8csl7z6dsycy3pszhrh35
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOWx0bEJYRWI1QzNwZzNG
            SGNVWjR0SnVjUjlnM1lOTEo1dmRmaHorMGxvClE4VFVXTDB0RnFvRGVKL1ZLMlZZ
            NG1uUzNIZlFOMTJKeHFpZGQrTFdYNDQKLS0tIDlNTzBTK0tDQS9zc0l4aklFMWgv
            aU9OdjUwWDZiSDhFdHpXM1N5cERFTVUKPfeXPpeURkeIv5tHNI81u8sZeU8T5A0D
            m1zy+HIGr7E1HEDE4baKi5uxPJCj3ctbkSiWfQg5JcP1KD6kTExqTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1smawm633jsv5qn2aye465j85rac2cu3h7fez3jpl2qu49fh56ejqdjusvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaWFRS3AxK25mSnZmb25r
            TURMbmRtbEFsSHhobVJMVWFvaEo5QVRsMWt3ClY1ak5WVFU4NzFvWC8xdndVOTRR
            TkJCR2FISkROMzdjYzVqcnYxT3ZGSjAKLS0tIElmMEFnMEhOTzhOdDUxNzduRXJ6
            T2gvc3RaRmFRK3UwVm5TMHFaMTBVQ0kKrgOwQDnjdZ2dbjBi3dpjLFokzkhPw7dy
            tf9y6F3YYjOLC0UAngLWgCwDkDGhTBeHI0nlzmrBUZJHvKOyBkeOtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T02:46:47Z"
    mac: ENC[AES256_GCM,data:n5SU8c2/g7wJHcWR2ROzrY4HVTOcd5U5LVc7bBdUYuUfJHcB5IQzmAfxl8mPtzfSOlwHQy9Cu5hXPNYSjKBGyz6rB/atdJeGOeiVBWXgaDQ1vcc8vRf3dW1IzOTkroi77iB/Idit/NMHbt69ecVudSMZeBdMMHB8vbLDBL64A/M=,iv:3kI0W8eaeJCMrT/iJgCa5+C1knwk5h6Px1SYg8fsr2I=,tag:LTNzzbtFgmGhloobzfbYHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
