db_password: ENC[AES256_GCM,data:6mzJiGSUcFbmN5236GsH3cXjTOo=,iv:E3PgLZZb7yUpH2m8QiC2RwZ9NW4KpA5lET1pnR8gEhg=,tag:wX2S8jTje7jhcXOMGWKrAw==,type:str]
smtp_password: ENC[AES256_GCM,data:wpxLZYSEhponHeQ7eMRG+0gGQw==,iv:usB3pSfQPQL8IOUYnHdEffACE7xjPq0gFXJUsCP0A+I=,tag:mZ9iNCbkarpj6Md9xGuMRw==,type:str]
aws_access_key_id: ENC[AES256_GCM,data:5jgcr9GPUD6IbthRNf1g1I5qUxE=,iv:AaJApCnA9HpLYo035wkrjbnQ5KlfqVWxwNcMUNL5FYk=,tag:oMT5hKNTfzYIv2JWh615+w==,type:str]
aws_secret_access_key: ENC[AES256_GCM,data:awkHd4DupOQiMGOtwFldchBGxj9R8rM9yAEdthmxwB3t2fgztR8XS66dfg==,iv:S+XvQvr78B/qkmAgumG1CxFH89qlvUAjqwT++bxDoiM=,tag:Z5ez9NWOkeJUu2keiZ+bMw==,type:str]
google_analytics_gtag: ENC[AES256_GCM,data:3moz29qnL2rUydxk,iv:qnAsnElTqQaKwYv7gbQuK8hy4Qjjf+/2/o9DsnI6CV8=,tag:dXxOVs4IUrJmy36E2T0a/A==,type:str]
db_readonly_password: ENC[AES256_GCM,data:ufMpG8hVN/0byy/F8FmsaTvN4/2OuC7K5o8f3tdm,iv:06YoYBs855D/3UM4f38MyefUm+mbciNsP3MAXos311k=,tag:UblVJFyeXk+LHDuTV2w5Gw==,type:str]
db_readwrite_password: ENC[AES256_GCM,data:jR9/AYvMtqc0iu8ygS0YGDnBINam2yhYBD8jFvFe,iv:r69XZ74DEiAEXgl7bgv9Ht2SykqpheY9M2OsGcLPueE=,tag:SWK2xX945j1AE0EriWBuHw==,type:str]
sops:
    age:
        - recipient: age1hm87e69thh5c4glk9w2gn2dn3mhexe7cen3c57upfg9zech9qe9sz0ha4j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseitJa1JzN082RkNaT1Bh
            b3lIMlpIWWMzN2FnUU1PSVEwKzUvamdzZ0ZjClZUNFJvQ2p0T0RZdUVYd1hNelp4
            SEFkd09jYm0zVTZOaXRNNzE3TU9xNWcKLS0tIDFQYU5yUHFVWnpuL2grdUcyKzFw
            TGtyOHJ5Skx5MmIwVTZVa3BsSmdLNW8KSgpk/lFQyuiiSxmO18QnFO+Mp0Mj/BN+
            F8GYP/4DQas9/Y73IUe99y0vTMlE/0/pg+DBthER1srGRM4LYt2uDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h9eclrfude5fkzvt0v7sjyhfsu5f839xw0wwh29lrptq70mfvgescqng6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QlZtakE0OU5QU1IvVk4z
            RFo4eTlzWGo4L2FOYmhmTkVkZXdYRTdEalc0CldNUWpSVXJjT2dmc2o2ZmY4QUs2
            aEtpMzNXQXl3aWVBdUdGZExwS3RlRlEKLS0tIGJEREFVNWRocjdCdEVoZmRjYTZR
            c3VuOTdHcDM3QldUTHp2bm9wYW93aTgK11U67piKsLRzchvnaNDz/Z8s9GVgpWrx
            iUkQmhtLZVbFSWPXw0iLUN2p6/cQLymbwLyylUauKJ2EAGDSq/s6Vg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1esadyxrm9kjt25jlg9y0mmp8u75mh05pncxxd8csl7z6dsycy3pszhrh35
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweWgySnpVSjVYVlNzWUxa
            eEJmQlJqeTNZTUR6Y21ucHRkK2l2YUhUT21ZCnBxTkpIVitLUWQrNWQ5azU3cG5U
            YkVPd1Y0K0Rvb1ZseUMrMUNjcUc5MDAKLS0tIHdQcXEwOExSM3VYQ0NQYm5aaFZ1
            TUN3MGdsdGg4YS9lMEhQU2FXWktBS3MKXNs2uWJBgg5aBtIWAOI247LQbc+Mpd2b
            21a0Sl4zBvFWdTrQynQaLUmW9iS+Lt/vRiIV3fmUPF6e9g9rRldHQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1smawm633jsv5qn2aye465j85rac2cu3h7fez3jpl2qu49fh56ejqdjusvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBME11VjJGaVVWYnV0ZjRu
            akMwU1hUZWdLZWRJaVNzeFI3cS9NdE9INUFrCkYvK2wxZ2NUTVVlbGp2M0loN0NU
            NnNMaDNEK1dGS3hoN3p3VUtZZEJZMXcKLS0tIDc4TDZsTW1TaUdUMG1KNmJkNnlm
            d2FUZG9pSm1QQ1BMcWpCaWdXU3NvdzQKwBnHGMTeCoHE1PqGWkcEtKspHprVfSFW
            RrHBRYyk0Etdc56sQUMcOoV47Wrf6l9D1D0UBvheHFCtrgcXJoXbkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T01:31:12Z"
    mac: ENC[AES256_GCM,data:k/ov4G0J3zkYSBwISNi+ZQMmk6TLwBFubtf8NlqeexOMKrOzbCYjX83mdbPxJBHN8rbS34Yha1yLLvVsyw/COdAHTNBAcf7rcr3T/u3ITn6ULrNfw0EBDVVNEliqbxbfKtAQs37Y8mBX2pdJdSOMYoY3b1g9fswtFkTXEj1di4M=,iv:OL7KGsm0U22KvGEJPSVlNvE3EUD/8mZJIOXspEe89vA=,tag:uBaspdKJN6TzkkvbTyIf1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
